name: 'Merge JSON'
description: 'Merge JSON data from one file into another'
inputs:
  input-file:  # new json data
    description: 'New JSON data file'
    required: true
    default: 'integration-manifest.json'
  library-file:  # master file
    description: 'File to receive merged JSON data'
    required: true
    default: 'master.json'
outputs:
  time: 
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'